# Set-up

In [1]:
#Import Libraries
import pandas as pd
import numpy as np

In [2]:
#Load the data and verify it loaded correctly.
df = pd.read_csv('LinkedIn_Job_Postings.csv')
df.head()

,Date,Company,Title,Job Description,Criteria
0,2021-11-04,Dignity Health,Patient Advocate,*Overview*\n\nDignity Health Medical Foundatio...,Seniority level\nAssociate\nEmployment type\nF...
1,2021-11-04,Centene Corporation,Disease Management Enrollment Representative,Position Purpose\n\nThe Disease Management Enr...,Seniority level\nNot Applicable\nEmployment ty...
2,2021-10-27,Dignity Health,Patient Logistics Coordinator,"*Overview*\n\nDignity Health, one of the natio...",Seniority level\nEntry level\nEmployment type\...
3,2021-10-20,Centene Corporation,Disease Management Assistant (HNGS),Position Purpose\n\nThe Disease Management Ass...,Seniority level\nNot Applicable\nEmployment ty...
4,2021-10-27,Dignity Health,Patient Logistics Coordinator,"*Overview*\n\nDignity Health, one of the natio...",Seniority level\nEntry level\nEmployment type\...

# Split Criteria

In [3]:
seniority = []
employment_type = []
job_function = []
industry = []

sen_s = 'Seniority level\n'
emp_s = '\nEmployment type\n'
jf_s = '\nJob function\n'
ind_s = '\nIndustries\n'

criteria = df['Criteria']

for s in criteria: 
    
    sen = s[s.find(sen_s)+len(sen_s):s.rfind(emp_s)]
    seniority.append(sen)

    emp = s[s.find(emp_s)+len(emp_s):s.rfind(jf_s)]
    employment_type.append(emp)
    
    jfunc = s[s.find(jf_s)+len(jf_s):s.rfind(ind_s)]
    job_function.append(jfunc)

    ind = s[s.find(ind_s)+len(ind_s):]
    industry.append(ind)

# Add Split Criteria to Dataframe

In [4]:
df['Seniority'] = seniority
df['Employment Type'] = employment_type
df['Job Function'] = job_function
df['Industry'] = industry

In [5]:
df.head()

,Date,Company,Title,Job Description,Criteria,Seniority,Employment Type,Job Function,Industry
0,2021-11-04,Dignity Health,Patient Advocate,*Overview*\n\nDignity Health Medical Foundatio...,Seniority level\nAssociate\nEmployment type\nF...,Associate,Full-time,Health Care Provider,"Nonprofit Organization Management, Health, Wel..."
1,2021-11-04,Centene Corporation,Disease Management Enrollment Representative,Position Purpose\n\nThe Disease Management Enr...,Seniority level\nNot Applicable\nEmployment ty...,Not Applicable,Full-time,Customer Service and Information Technology,Hospital & Health Care and Insurance
2,2021-10-27,Dignity Health,Patient Logistics Coordinator,"*Overview*\n\nDignity Health, one of the natio...",Seniority level\nEntry level\nEmployment type\...,Entry level,Full-time,Management and Manufacturing,"Nonprofit Organization Management, Health, Wel..."
3,2021-10-20,Centene Corporation,Disease Management Assistant (HNGS),Position Purpose\n\nThe Disease Management Ass...,Seniority level\nNot Applicable\nEmployment ty...,Not Applicable,Contract,Administrative,Hospital & Health Care and Insurance
4,2021-10-27,Dignity Health,Patient Logistics Coordinator,"*Overview*\n\nDignity Health, one of the natio...",Seniority level\nEntry level\nEmployment type\...,Entry level,Full-time,Management and Manufacturing,"Nonprofit Organization Management, Health, Wel..."

# Explore the New Columns and Perform Any Other Cleaning Tasks

## Seniority

In [6]:
print(df['Seniority'].value_counts())

Entry level                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                389
Associate                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  221
Not Applicable                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             192
Mid-Senior level                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            99
\nFull-tim                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  14
Director                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    14
Internship                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  11
Executive                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3
          \n          \n            Not Applicable\n          \n        \n      \n        \n          Employment type\n        \n        \n          Full-time\n        \n      \n        \n          \n            Job function\n          \n          \n            Project Management and Information Technology\n          \n        \n        \n          \n            Industries\n          \n          \n          Construction\n          \n        \n                                              1
\nTemporar                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
\nOthe                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
\nContrac                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
          \n          \n            Entry level\n          \n        \n      \n        \n          Employment type\n        \n        \n          Contract\n        \n      \n        \n          \n            Job function\n          \n          \n            Health Care Provider\n          \n        \n        \n          \n            Industries\n          \n          \n          Information Technology and Services, Computer Software, and Financial Services\n          \n        \n         1
Name: Seniority, dtype: int64

###### There are some obviously odd things happening here. Lets explore further to figure out the best way to resolve the problems.

In [7]:
df[df['Seniority']=='\nFull-tim']

,Date,Company,Title,Job Description,Criteria,Seniority,Employment Type,Job Function,Industry
26,2021-11-02,"Creative Recreational Systems, Inc",Executive Administrative Assistant,Executive Administrative Assistant\n\n$22-$29/...,Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
71,2021-10-19,"CENTRAL STRIPING SERVICE, INC.",Construction Project Manager,PROJECT MANAGER:\n\nResponsible for overseeing...,Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
93,2021-10-27,Fortuna BMC,Data Entry Clerk,The Data Entry Specialist will use a PC workst...,Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
130,2021-10-29,"U.S. Lawns - Sacramento East and Elk Grove, CA",Business Developer,U.S. Lawns is currently trying looking to grow...,Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
173,2021-11-06,Tri Tool Technologies,Controls Engineer,DESCRIPTION: \n\nAre you ignited by innovation...,Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
183,2021-11-06,Tri Tool Technologies,Mechanical Engineer II,DESCRIPTION:\n\nAre you ignited by innovation?...,Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
226,2021-10-28,Travelers,Medical Case Manager,Provide office based telephonic medical case m...,Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
266,2021-11-07,Atelier Staffing,Hotel Specialist,\n *Overview*Dignity Health operates si...,Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
336,2021-10-11,Farmers Insurance,Customer Service Representative,\n You could be the one who changes eve...,Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
361,2021-11-06,Tri Tool Technologies,Senior Mechanical Engineer,\n DESCRIPTION: Are you ignited by inno...,Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
362,2021-10-12,Teledyne Defense Electronics,Planning Supervisor,"\n Plans, organizes, directs, and coord...",Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
400,2021-10-13,Proscapes Landscape and design,Designer/ Project Manager,"\n ProScapes Landscape & Design, Inc. i...",Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
423,2021-10-28,Pacific Coast Building Products,Staff Accountant II,"\n Pacific Coast Companies, Inc. is a d...",Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time
458,2021-10-11,Environmental Landscape Solutions,Landscape Estimator,\n Required Skills:Minimum 4 years’ exp...,Employment type\nFull-time,\nFull-tim,Full-tim,pe\nFull-tim,type\nFull-time

In [8]:
df[df['Seniority']=='\nTemporar']

,Date,Company,Title,Job Description,Criteria,Seniority,Employment Type,Job Function,Industry
65,2021-10-18,Sacramento Marriott Rancho Cordova,Front Desk Agent - FT & PT,The Sacramento Marriott located in Rancho Cord...,Employment type\nTemporary,\nTemporar,Temporar,pe\nTemporar,type\nTemporary

In [9]:
df[df['Seniority']=='\nOthe']

,Date,Company,Title,Job Description,Criteria,Seniority,Employment Type,Job Function,Industry
123,2021-10-21,Commercial Sign Crafters,Administrative,Looking for an experienced person from the sig...,Employment type\nOther,\nOthe,Othe,pe\nOthe,type\nOther

In [10]:
df[df['Seniority']=='\nContrac']

,Date,Company,Title,Job Description,Criteria,Seniority,Employment Type,Job Function,Industry
39,2021-11-03,Fortuna BMC,Data Entry Supervisor,Description:\n\n• Key Data Entry (KDE) Supervi...,Employment type\nContract,\nContrac,Contrac,pe\nContrac,type\nContract

### The above instances are all a result of missing values for 'Seniority'.

In [11]:
#Indicate missing values.
df['Seniority'] = df['Seniority'].str.replace('\nFull-tim', 'NaN')
df['Seniority'] = df['Seniority'].str.replace('\nTemporar', 'NaN')
df['Seniority'] = df['Seniority'].str.replace('\nOthe', 'NaN')
df['Seniority'] = df['Seniority'].str.replace('\nContrac', 'NaN')

### The following instances have data can be replaced with a clean value.

In [12]:
df[df['Seniority']=='          \n          \n            Entry level\n          \n        \n      \n        \n          Employment type\n        \n        \n          Contract\n        \n      \n        \n          \n            Job function\n          \n          \n            Health Care Provider\n          \n        \n        \n          \n            Industries\n          \n          \n          Information Technology and Services, Computer Software, and Financial Services\n          \n        \n   ']

,Date,Company,Title,Job Description,Criteria,Seniority,Employment Type,Job Function,Industry
340,2021-10-12,HD Supply,Warehouse Associate- Immediate Hire!,\n Clinical Support Coordinator Associa...,\n \n \n Seniority ...,\n \n Entry leve...,\n Seniority level\n \...,\n Seniority level\n ...,\n Seniority level\n ...

In [13]:
df.loc[340, 'Seniority'] = 'Entry level'

In [14]:
df[df['Seniority']=='          \n          \n            Not Applicable\n          \n        \n      \n        \n          Employment type\n        \n        \n          Full-time\n        \n      \n        \n          \n            Job function\n          \n          \n            Project Management and Information Technology\n          \n        \n        \n          \n            Industries\n          \n          \n          Construction\n          \n        \n   ']

,Date,Company,Title,Job Description,Criteria,Seniority,Employment Type,Job Function,Industry
442,2021-10-21,"Patriot Construction, Inc..",Site Superintendent,\n Job DescriptionELECTRICAL PROJECT MA...,\n \n \n Seniority ...,\n \n Not Applic...,\n Seniority level\n \...,\n Seniority level\n ...,\n Seniority level\n ...

In [15]:
df.loc[442, 'Seniority'] = 'Not Applicable'

### Verify that Seniority is Clean

In [16]:
print(df['Seniority'].value_counts())

Entry level         390
Associate           221
Not Applicable      193
Mid-Senior level     99
NaN                  17
Director             14
Internship           11
Executive             3
Name: Seniority, dtype: int64

These are all acceptable values and no further cleaning is required.

## Employment Type

In [17]:
print(df['Employment Type'].value_counts())

Full-time                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     779
Part-time                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      64
Contract                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       47
Other                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          22
Full-tim                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       14
Temporary                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      10
Volunteer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       4
Internship                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      3
    \n            Seniority level\n          \n          \n            Entry level\n          \n        \n      \n        \n          Employment type\n        \n        \n          Contract\n        \n      \n        \n          \n            Job function\n          \n          \n            Health Care Provider\n          \n        \n        \n          \n            Industries\n          \n          \n          Information Technology and Services, Computer Software, and Financial Services\n          \n        \n         1
Othe                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
    \n            Seniority level\n          \n          \n            Not Applicable\n          \n        \n      \n        \n          Employment type\n        \n        \n          Full-time\n        \n      \n        \n          \n            Job function\n          \n          \n            Project Management and Information Technology\n          \n        \n        \n          \n            Industries\n          \n          \n          Construction\n          \n        \n                                              1
Contrac                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Temporar                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Name: Employment Type, dtype: int64

In [18]:
#Fix categories that are mispelled.
df['Employment Type'] = df['Employment Type'].str.replace('Full-tim', 'Full-time')
df['Employment Type'] = df['Employment Type'].str.replace('Full-timee', 'Full-time')

In [19]:
df['Employment Type'] = df['Employment Type'].str.replace('Temporar', 'Temporary')
df['Employment Type'] = df['Employment Type'].str.replace('Temporaryy', 'Temporary')

In [20]:
df['Employment Type'] = df['Employment Type'].str.replace('Contrac', 'Contract')
df['Employment Type'] = df['Employment Type'].str.replace('Contractt', 'Contract')

In [21]:
df['Employment Type'] = df['Employment Type'].str.replace('Othe', 'Other')
df['Employment Type'] = df['Employment Type'].str.replace('Otherr', 'Other')

In [22]:
#Fix the same two rows as before.
df.loc[340, 'Employment Type'] = 'Contract'
df.loc[442, 'Employment Type'] = 'Full-time'

In [23]:
print(df['Employment Type'].value_counts())

Full-time     794
Part-time      64
Contract       49
Other          23
Temporary      11
Volunteer       4
Internship      3
Name: Employment Type, dtype: int64

## Job Function

In [24]:
df['Job Function'].value_counts()

Health Care Provider                                             151
Management and Manufacturing                                     146
Sales and Business Development                                    74
Engineering and Information Technology                            63
Other                                                             59
                                                                ...
Accounting/Auditing, Finance, and Strategy/Planning                1
Health Care Provider and Customer Service                          1
Customer Service, Administrative, and Management                   1
pe\nTemporar                                                       1
Customer Service, Quality Assurance, and Health Care Provider      1
Name: Job Function, Length: 71, dtype: int64

In [25]:
#Make missing values consistent.
df['Job Function'] = df['Job Function'].str.replace('pe\nFull-tim', 'NaN')
df['Job Function'] = df['Job Function'].str.replace('pe\nContrac', 'NaN')
df['Job Function'] = df['Job Function'].str.replace('pe\nTemporar', 'NaN')
df['Job Function'] = df['Job Function'].str.replace('pe\nOthe', 'NaN')

In [26]:
#Fix the broken values.
df.loc[340, 'Job Function'] = 'Health Care Provider'
df.loc[442, 'Job Function'] = 'Project Management and Information Technology'

In [27]:
df['Job Function'].unique()

array(['Health Care Provider',
       'Customer Service and Information Technology',
       'Management and Manufacturing', 'Administrative',
       'Accounting/Auditing and Finance', 'Human Resources',
       'Marketing, Public Relations, and Writing/Editing',
       'Education and Training', 'Design, Consulting, and Engineering',
       'Other', 'Finance and Sales', 'NaN', 'Sales',
       'Administrative, Business Development, and Customer Service',
       'Information Technology', 'Business Development and Sales',
       'Engineering and Information Technology', 'Quality Assurance',
       'Marketing and Sales',
       'Research, Analyst, and Information Technology',
       'Sales and Business Development',
       'Project Management and Information Technology',
       'Customer Service',
       'General Business, Finance, and Accounting/Auditing',
       'Administrative, Customer Service, and Accounting/Auditing',
       'Purchasing and Supply Chain', 'General Business',
       'Distribution, Purchasing, and Supply Chain',
       'Accounting/Auditing', 'Science and Health Care Provider',
       'Customer Service, Administrative, and Management',
       'Consulting, Information Technology, and Sales',
       'Customer Service, Quality Assurance, and Health Care Provider',
       'Accounting/Auditing, Administrative, and Customer Service',
       'Accounting/Auditing, Finance, and Management',
       'Sales, Business Development, and Management', 'Management',
       'Legal', 'Marketing', 'Training',
       'Information Technology, Project Management, and Consulting',
       'Design, Art/Creative, and Information Technology',
       'General Business and Customer Service', 'Purchasing',
       'Product Management and Marketing', 'Engineering',
       'Sales and Customer Service',
       'Other, Information Technology, and Management',
       'Production and Manufacturing',
       'Quality Assurance, Manufacturing, and Customer Service',
       'Project Management',
       'Project Management, General Business, and Management',
       'Sales and Management', 'Production',
       'Sales, General Business, and Finance',
       'Administrative and Customer Service',
       'Management, Consulting, and Engineering',
       'Accounting/Auditing, Finance, and Strategy/Planning', 'Education',
       'Distribution and Supply Chain', 'Customer Service and Other',
       'Health Care Provider and Customer Service',
       'Health Care Provider and Consulting',
       'Sales, Business Development, and Education',
       'Design and Information Technology',
       'Distribution, Other, and Customer Service'], dtype=object)

##### This is a good start for this. Further steps may involve breaking up or summarizing the multi-function descriptions.

## Industry

In [28]:
df['Industry'].value_counts()

Hospital & Health Care and Insurance                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                74
Nonprofit Organization Management, Health, Wellness and Fitness, and Hospital & Health Care                                                                                                                                                                                                                                                                                                                                                                                                                                                         57
Health, Wellness and Fitness, Hospital & Health Care, and Medical Practice                                                                                                                                                                                                                                                                                                                                                                                                                                                                          51
Retail                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              41
Information Technology and Services, Financial Services, and Hospital & Health Care                                                                                                                                                                                                                                                                                                                                                                                                                                                                 28
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ..
Construction, Hospital & Health Care, and Hospitality                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
Broadcast Media                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
         \n            Seniority level\n          \n          \n            Entry level\n          \n        \n      \n        \n          Employment type\n        \n        \n          Contract\n        \n      \n        \n          \n            Job function\n          \n          \n            Health Care Provider\n          \n        \n        \n          \n            Industries\n          \n          \n          Information Technology and Services, Computer Software, and Financial Services\n          \n        \n         1
Oil & Energy, Utilities, and Electrical/Electronic Manufacturing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
Hospital & Health Care and Information Technology and Services                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Name: Industry, Length: 179, dtype: int64

In [29]:
#Make missing values consistent.
df['Industry'] = df['Industry'].str.replace('type\nFull-time', 'NaN')
df['Industry'] = df['Industry'].str.replace('type\nContract', 'NaN')
df['Industry'] = df['Industry'].str.replace('type\nTemporary', 'NaN')
df['Industry'] = df['Industry'].str.replace('pe\nOthe', 'NaN')

In [30]:
#Fix the broken values.
df.loc[340, 'Industry'] = 'Information Technology and Services, Computer Software, and Financial Services'
df.loc[442, 'Industry'] = 'Construction'

In [31]:
df['Industry'].unique()

array(['Nonprofit Organization Management, Health, Wellness and Fitness, and Hospital & Health Care',
       'Hospital & Health Care and Insurance',
       'Nonprofit Organization Management, Higher Education, and Mental Health Care',
       'Construction, Information Technology and Services, and Civil Engineering',
       'Information Technology and Services, Financial Services, and Hospital & Health Care',
       'Military', 'NaN',
       'Health, Wellness and Fitness, Hospital & Health Care, and Medical Practice',
       'Pharmaceuticals and Biotechnology',
       'Insurance, Financial Services, and Hospital & Health Care',
       'Insurance', 'Human Resources, Retail, and Financial Services',
       'Food & Beverages, Leisure, Travel & Tourism, and Hospitality',
       'Construction, Machinery, and Staffing and Recruiting',
       'Transportation/Trucking/Railroad',
       'Law Practice, Insurance, and Legal Services', 'Hospitality',
       'Marketing and Advertising', 'Food & Beverages',
       'Facilities Services, Utilities, and Hospitality',
       'Staffing and Recruiting, Health, Wellness and Fitness, and Hospital & Health Care',
       'Environmental Services', 'Information Technology and Services',
       'Retail', 'Civil Engineering',
       'Chemicals, Biotechnology, and Pharmaceuticals',
       'Financial Services',
       'Automotive, Machinery, and Staffing and Recruiting',
       'Information Technology and Services, Computer Software, and Financial Services',
       'Marketing and Advertising, Information Technology and Services, and Computer Software',
       'Construction, Staffing and Recruiting, and Oil & Energy',
       'Utilities',
       'Marketing and Advertising, Management Consulting, and Financial Services',
       'Construction, Marketing and Advertising, and Computer Software',
       'tyNaNr', 'Construction, Consumer Goods, and Retail',
       'Construction, Staffing and Recruiting, and Financial Services',
       'Banking, Financial Services, and Real Estate',
       'Staffing and Recruiting, Banking, and Financial Services',
       'Health, Wellness and Fitness, Medical Practice, and Hospital & Health Care',
       'Printing',
       'Construction, Civil Engineering, and Nonprofit Organization Management',
       'Internet',
       'Construction, Civil Engineering, and Environmental Services',
       'Construction, Financial Services, and Transportation/Trucking/Railroad',
       'Automotive', 'Staffing and Recruiting',
       'Business Supplies and Equipment',
       'Information Technology and Services, Computer Software, and Telecommunications',
       'Food & Beverages, Food Production, and Retail',
       'Construction, Machinery, and Mechanical or Industrial Engineering',
       'Hospital & Health Care',
       'Staffing and Recruiting, Financial Services, and Hospital & Health Care',
       'Wholesale, Automotive, and Machinery',
       'Insurance and Financial Services',
       'Construction, Building Materials, and Consumer Services',
       'Biotechnology and Medical Devices',
       'Construction, Renewables & Environment, and Electrical/Electronic Manufacturing',
       'Construction, Insurance, and Financial Services',
       'Civil Engineering, Environmental Services, and Management Consulting',
       'Information Technology and Services, Logistics and Supply Chain, and Financial Services',
       'Construction, Staffing and Recruiting, and Retail',
       'Building Materials',
       'Staffing and Recruiting, Insurance, and Hospital & Health Care',
       'Insurance, Health, Wellness and Fitness, and Medical Practice',
       'Nonprofit Organization Management, Education Management, and Maritime',
       'Electrical/Electronic Manufacturing',
       'Food & Beverages, Retail, and Hospitality', 'Facilities Services',
       'Construction, Automotive, and Staffing and Recruiting',
       'Marketing and Advertising, Insurance, and Financial Services',
       'Information Technology and Services, Banking, and Financial Services',
       'Construction, Telecommunications, and Transportation/Trucking/Railroad',
       'Retail and Supermarkets',
       'Insurance and Government Administration',
       'Financial Services and Accounting',
       'Wireless, Telecommunications, and Construction',
       'Information Technology and Services, Computer Networking, and Computer & Network Security',
       'Construction, Information Technology and Services, and Financial Services',
       'Electrical/Electronic Manufacturing, Construction, and Mechanical or Industrial Engineering',
       'Biotechnology, Pharmaceuticals, and Medical Devices',
       'Individual & Family Services, Mental Health Care, and Hospital & Health Care',
       'Construction', 'Construction, Automotive, and Retail',
       'Hospital & Health Care, Medical Devices, and Mental Health Care',
       'Construction, Staffing and Recruiting, and Hospital & Health Care',
       'Utilities, Construction, and Executive Office',
       'Consumer Services, Architecture & Planning, and Construction',
       'Marketing and Advertising, Consumer Goods, and Retail',
       'Broadcast Media',
       'Information Technology and Services, Retail, and Financial Services',
       'Renewables & Environment, Construction, and Civil Engineering',
       'Construction, Architecture & Planning, and Civil Engineering',
       'Nonprofit Organization Management, Management Consulting, and Hospital & Health Care',
       'Restaurants, Food & Beverages, and Retail',
       'Construction, Hospital & Health Care, and Hospitality',
       'Construction, Marketing and Advertising, and Consumer Services',
       'Financial Services, Health, Wellness and Fitness, and Hospital & Health Care',
       'Individual & Family Services',
       'Information Technology and Services and Management Consulting',
       'Staffing and Recruiting, Human Resources, and Management Consulting',
       'Financial Services and Retail', 'Retail and Consumer Goods',
       'Computer Software, Information Technology and Services, and Computer Games',
       'Education Management, Mental Health Care, and Hospital & Health Care',
       'Construction, Wholesale, and Retail',
       'Telecommunications, Retail, and Financial Services',
       'Construction, Wholesale, and Transportation/Trucking/Railroad',
       'Construction, Retail, and Financial Services',
       'Construction, Civil Engineering, and Oil & Energy',
       'Medical Devices, Biotechnology, and Pharmaceuticals',
       'Apparel & Fashion, Consumer Goods, and Retail', 'Wholesale',
       'Human Resources, Leisure, Travel & Tourism, and Hospitality',
       'Automotive and Information Technology and Services',
       'Apparel & Fashion, Wholesale, and Retail',
       'Computer & Network Security, Computer Hardware, and Computer Software',
       'Real Estate, Leisure, Travel & Tourism, and Hospitality',
       'Retail, Consumer Services, and Health, Wellness and Fitness',
       'Construction, Automotive, and Consumer Services',
       'Health, Wellness and Fitness, Retail, and Pharmaceuticals',
       'Computer Hardware, Computer Software, and Computer Networking',
       'Construction, Environmental Services, and Transportation/Trucking/Railroad',
       'Information Technology and Services, Computer Software, and Computer & Network Security',
       'Financial Services, Insurance, and Consumer Services',
       'Environmental Services and Hospital & Health Care',
       'Information Technology and Services, Automotive, and Retail',
       'Automotive, Insurance, and Financial Services',
       'Construction, Automotive, and Transportation/Trucking/Railroad',
       'Apparel & Fashion',
       'Construction, Civil Engineering, and Financial Services',
       'Restaurants, Food & Beverages, and Hospitality',
       'Consumer Services, Real Estate, and Hospitality',
       'Retail, Consumer Goods, and Supermarkets', 'Consumer Goods',
       'Nonprofit Organization Management, Individual & Family Services, and Mental Health Care',
       'Staffing and Recruiting, Retail, and Consumer Services',
       'Automotive, Industrial Automation, and Retail',
       'Construction, Retail, and Transportation/Trucking/Railroad',
       'Construction, Retail, and Health, Wellness and Fitness',
       'Security and Investigations',
       'Retail, Financial Services, and Hospital & Health Care',
       'Logistics and Supply Chain, Retail, and Transportation/Trucking/Railroad',
       'Information Technology and Services and Hospital & Health Care',
       'Veterinary, Health, Wellness and Fitness, and Hospital & Health Care',
       'Wholesale, Consumer Goods, and Retail',
       'Medical Practice, Hospital & Health Care, and Pharmaceuticals',
       'Oil & Energy, Utilities, and Electrical/Electronic Manufacturing',
       'Construction, Consumer Services, and Transportation/Trucking/Railroad',
       'Construction, Nonprofit Organization Management, and Hospital & Health Care',
       'Food & Beverages, Retail, and Transportation/Trucking/Railroad',
       'Automotive and Retail', 'Mental Health Care',
       'Security and Investigations, Consumer Services, and Government Administration',
       'Construction, Automotive, and Machinery', 'Wholesale and Retail',
       'Primary/Secondary Education',
       'Marketing and Advertising, Retail, and Consumer Services',
       'Financial Services and Investment Management',
       'Defense & Space, Public Safety, and Security and Investigations',
       'Hospital & Health Care, Insurance, and Management Consulting',
       'Law Enforcement, Professional Training & Coaching, and Security and Investigations',
       'Civic & Social Organization and Nonprofit Organization Management',
       'Construction, Automotive, and Financial Services',
       'Hospital & Health Care and Information Technology and Services',
       'Hospital & Health Care, Pharmaceuticals, and Health, Wellness and Fitness',
       'Construction, Facilities Services, and Real Estate',
       'Individual & Family Services and Nonprofit Organization Management',
       'Hospital & Health Care and Medical Practice',
       'Information Technology and Services, Internet, and Staffing and Recruiting',
       'Management Consulting',
       'Health, Wellness and Fitness, Insurance, and Medical Practice',
       'Medical Practice',
       'Information Services, Education Management, and Consumer Services',
       'Logistics and Supply Chain, Mechanical or Industrial Engineering, and Warehousing'],
      dtype=object)

#### This category will need more work, but everything has a functional value now.

# Getting Years Experience from Job Description

In [32]:
import string

#### Years Experience from Numeric Value

In [33]:
years_list = []

for s in df['Job Description']:
    
    for char in string.punctuation:
        s = s.replace(char,'')
    
    s = s.replace('\n', ' ')
    
    nums = [int(i) for i in s.split() if i.isdigit()]
    
    num_test = []
    
    for i in nums:
        if i < 11:
            num_test.append(i)
        else:
            pass
    
    if num_test:
        max_num = max(num_test)
    else:
        max_num = 'NaN'
    
    years_list.append(max_num)

In [34]:
from collections import Counter
Counter(years_list)

Counter({3: 98,
         'NaN': 399,
         2: 87,
         10: 64,
         1: 75,
         5: 112,
         4: 26,
         9: 17,
         7: 15,
         8: 22,
         6: 33})

In [35]:
df['Years Experience'] = years_list

#### Years of Experience from Word

In [45]:
alpha_years_list = []

alpha_num = ['one', 'two', 'three', 'four', 'five', 
             'six', 'seven', 'eight','nine']

for s in df['Job Description']:
    
    for char in string.punctuation:
        s = s.replace(char,'')
    
    s = s.replace('\n', ' ')
    s = s.lower()
    
    test_alpha_num = [anum in s for anum in alpha_num]
    
    true_alpha_num = [i for i, x in enumerate(test_alpha_num) if x]
    
    if true_alpha_num:
        max_num = max(true_alpha_num) + 1
    else:
        max_num = 'NaN'
    
    alpha_years_list.append(max_num)

In [47]:
Counter(alpha_years_list)

Counter({3: 43,
         2: 166,
         1: 383,
         'NaN': 181,
         6: 41,
         5: 60,
         8: 46,
         4: 20,
         9: 7,
         7: 1})

In [48]:
df['Years Experience Two'] = alpha_years_list

In [53]:
df['Experience'] = np.where(df['Years Experience']=='NaN', df['Years Experience Two'], 
                           df['Years Experience'])

In [54]:
df.head()

,Date,Company,Title,Job Description,Criteria,Seniority,Employment Type,Job Function,Industry,Years Experience,Years Experience Two,Experience
0,2021-11-04,Dignity Health,Patient Advocate,*Overview*\n\nDignity Health Medical Foundatio...,Seniority level\nAssociate\nEmployment type\nF...,Associate,Full-time,Health Care Provider,"Nonprofit Organization Management, Health, Wel...",3,3,3
1,2021-11-04,Centene Corporation,Disease Management Enrollment Representative,Position Purpose\n\nThe Disease Management Enr...,Seniority level\nNot Applicable\nEmployment ty...,Not Applicable,Full-time,Customer Service and Information Technology,Hospital & Health Care and Insurance,NaN,3,3
2,2021-10-27,Dignity Health,Patient Logistics Coordinator,"*Overview*\n\nDignity Health, one of the natio...",Seniority level\nEntry level\nEmployment type\...,Entry level,Full-time,Management and Manufacturing,"Nonprofit Organization Management, Health, Wel...",2,2,2
3,2021-10-20,Centene Corporation,Disease Management Assistant (HNGS),Position Purpose\n\nThe Disease Management Ass...,Seniority level\nNot Applicable\nEmployment ty...,Not Applicable,Contract,Administrative,Hospital & Health Care and Insurance,NaN,3,3
4,2021-10-27,Dignity Health,Patient Logistics Coordinator,"*Overview*\n\nDignity Health, one of the natio...",Seniority level\nEntry level\nEmployment type\...,Entry level,Full-time,Management and Manufacturing,"Nonprofit Organization Management, Health, Wel...",2,2,2

In [55]:
df['Experience'].value_counts()

1      256
2      138
5      127
3      113
NaN     95
10      64
6       47
8       38
4       35
9       20
7       15
Name: Experience, dtype: int64

In [58]:
df = df.drop(['Years Experience','Years Experience Two'], axis=1)
df.head()

,Date,Company,Title,Job Description,Criteria,Seniority,Employment Type,Job Function,Industry,Experience
0,2021-11-04,Dignity Health,Patient Advocate,*Overview*\n\nDignity Health Medical Foundatio...,Seniority level\nAssociate\nEmployment type\nF...,Associate,Full-time,Health Care Provider,"Nonprofit Organization Management, Health, Wel...",3
1,2021-11-04,Centene Corporation,Disease Management Enrollment Representative,Position Purpose\n\nThe Disease Management Enr...,Seniority level\nNot Applicable\nEmployment ty...,Not Applicable,Full-time,Customer Service and Information Technology,Hospital & Health Care and Insurance,3
2,2021-10-27,Dignity Health,Patient Logistics Coordinator,"*Overview*\n\nDignity Health, one of the natio...",Seniority level\nEntry level\nEmployment type\...,Entry level,Full-time,Management and Manufacturing,"Nonprofit Organization Management, Health, Wel...",2
3,2021-10-20,Centene Corporation,Disease Management Assistant (HNGS),Position Purpose\n\nThe Disease Management Ass...,Seniority level\nNot Applicable\nEmployment ty...,Not Applicable,Contract,Administrative,Hospital & Health Care and Insurance,3
4,2021-10-27,Dignity Health,Patient Logistics Coordinator,"*Overview*\n\nDignity Health, one of the natio...",Seniority level\nEntry level\nEmployment type\...,Entry level,Full-time,Management and Manufacturing,"Nonprofit Organization Management, Health, Wel...",2

In [59]:
df.to_csv('job_posts_clean_ish.csv')